//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEViajaMas
{
    using System;
    using System.Collections.Generic;
    
    public partial class avion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public avion()
        {
            this.vuelo = new HashSet<vuelo>();
        }
    
        public int id_avion { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string model { get; set; }
        public string aerolinea { get; set; }
        public string placa { get; set; }
        public Nullable<int> millas_recorridas { get; set; }
        public Nullable<int> anio_ensamble { get; set; }
        public string estado { get; set; }
    
        public virtual empresa empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vuelo> vuelo { get; set; }
    }
}
