//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEViajaMas
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public checkin()
        {
            this.checkout = new HashSet<checkout>();
        }
    
        public int id_checkin { get; set; }
        public Nullable<int> id_reserva { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual reserva reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<checkout> checkout { get; set; }
    }
}
