//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEViajaMas
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkout
    {
        public int id_checkout { get; set; }
        public Nullable<int> id_checkin { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual checkin checkin { get; set; }
    }
}
