//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEViajaMas
{
    using System;
    using System.Collections.Generic;
    
    public partial class cupon
    {
        public int id_cupon { get; set; }
        public Nullable<int> id_reserva { get; set; }
    
        public virtual reserva reserva { get; set; }
    }
}
