//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEViajaMas
{
    using System;
    using System.Collections.Generic;
    
    public partial class detReserva
    {
        public Nullable<int> id_reserva { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> estado { get; set; }
        public int id { get; set; }
    
        public virtual reserva reserva { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
