//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEViajaMas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViajaMasEntities : DbContext
    {
        public ViajaMasEntities()
            : base("name=ViajaMasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<auto> auto { get; set; }
        public virtual DbSet<avion> avion { get; set; }
        public virtual DbSet<checkin> checkin { get; set; }
        public virtual DbSet<checkout> checkout { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<comentario> comentario { get; set; }
        public virtual DbSet<cupon> cupon { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<detReserva> detReserva { get; set; }
        public virtual DbSet<devDevol> devDevol { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<habitacion> habitacion { get; set; }
        public virtual DbSet<hotel> hotel { get; set; }
        public virtual DbSet<pago> pago { get; set; }
        public virtual DbSet<reserva> reserva { get; set; }
        public virtual DbSet<seguro> seguro { get; set; }
        public virtual DbSet<servicio> servicio { get; set; }
        public virtual DbSet<vuelo> vuelo { get; set; }
    }
}
