//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEViajaMas
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotel()
        {
            this.habitacion = new HashSet<habitacion>();
        }
    
        public int id_hotel { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public string nombre_hotel { get; set; }
        public Nullable<int> num_estrellas { get; set; }
        public string direccion { get; set; }
        public Nullable<int> num_cuartos { get; set; }
        public string estado { get; set; }
    
        public virtual empresa empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<habitacion> habitacion { get; set; }
    }
}
