//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEViajaMas
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servicio()
        {
            this.comentario = new HashSet<comentario>();
            this.detReserva = new HashSet<detReserva>();
        }
    
        public int id_servicio { get; set; }
        public Nullable<int> id_habitacion { get; set; }
        public Nullable<int> id_vuelo { get; set; }
        public Nullable<int> id_auto { get; set; }
        public Nullable<int> id_seguro { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> descuento { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> activo { get; set; }
    
        public virtual auto auto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comentario> comentario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detReserva> detReserva { get; set; }
        public virtual habitacion habitacion { get; set; }
        public virtual seguro seguro { get; set; }
        public virtual vuelo vuelo { get; set; }
    }
}
