//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEViajaMas
{
    using System;
    using System.Collections.Generic;
    
    public partial class vuelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vuelo()
        {
            this.servicio = new HashSet<servicio>();
        }
    
        public int id_vuelo { get; set; }
        public Nullable<int> id_departamento_origen { get; set; }
        public Nullable<int> id_departamento_destino { get; set; }
        public Nullable<int> id_avion { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public string estado { get; set; }
        public Nullable<int> capacidad { get; set; }
    
        public virtual avion avion { get; set; }
        public virtual departamento departamento { get; set; }
        public virtual departamento departamento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicio> servicio { get; set; }
    }
}
